name: Build Nova TV+ APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      # We added a wildcard to find gradlew even if it's inside a subfolder
      - name: Make gradlew executable
        run: chmod +x */gradlew || chmod +x gradlew

      # We added a command to run gradle from the correct folder
      - name: Build APK
        run: |
          if [ -d "NovaTVPlus" ]; then
            cd NovaTVPlus
          fi
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NovaTV-Plus-APK
          # We added a wildcard to find the APK no matter where it built
          path: "**/app/build/outputs/apk/debug/*.apk"
